### Ir a la pagina principal
GET http://localhost:3000
### Login request
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "cameron@mutiny.com",
    "password": "pR5&mW3D$"
}
### conteido aculto:
GET http://localhost:3000/contenido-oculto

### eliminar cookies
GET http://localhost:3000/eliminarcookie